In [309]:
import numpy as np
import pandas as pd
from datetime import datetime as dt
import itertools

In [330]:
loc="datasets\\"
# raw_data_1=pd.read_csv(loc+"2017-18.csv")
raw_data_2=pd.read_csv(loc+"2016-17.csv")
raw_data_3=pd.read_csv(loc+"2015-16.csv")
raw_data_4=pd.read_csv(loc+"2014-15.csv")
raw_data_5=pd.read_csv(loc+"2013-14.csv")
raw_data_6=pd.read_csv(loc+"2012-13.csv")
raw_data_7=pd.read_csv(loc+"2011-12.csv")
raw_data_8=pd.read_csv(loc+"2010-11.csv")

In [331]:
# print(len(raw_data_1.columns))
print(len(raw_data_2.columns))
print(len(raw_data_3.columns))
print(len(raw_data_4.columns))
print(len(raw_data_5.columns))
print(len(raw_data_6.columns))
print(len(raw_data_7.columns))
print(len(raw_data_8.columns))

# print(sum(raw_data_1.columns==raw_data_2.columns))
# print(sum(raw_data_1.columns==raw_data_3.columns))
print(sum(raw_data_3.columns==raw_data_2.columns))

65
65
68
68
74
71
71
65

dtype('O')

In [332]:
def parse_date(date):
#     print(type(date))
    data=str(date)
    print(type(date))
    print(date)
    if date=="":
        return None
    else:
        return dt.strptime(date,"%d/%m/%y").date()
    
# raw_data_1.Date=raw_data_1.Date.apply(parse_date)
# raw_data_2.Date=raw_data_2.Date.apply(parse_date)
# raw_data_3.Date=raw_data_3.Date.apply(parse_date)
raw_data_4.Date=raw_data_4.Date.apply(parse_date)
raw_data_5.Date=raw_data_5.Date.apply(parse_date)
raw_data_6.Date=raw_data_6.Date.apply(parse_date)
raw_data_7.Date=raw_data_7.Date.apply(parse_date)
raw_data_8.Date=raw_data_8.Date.apply(parse_date)

<class 'str'>
16/08/14
<class 'str'>
16/08/14
<class 'str'>
16/08/14
<class 'str'>
16/08/14
<class 'str'>
16/08/14
<class 'str'>
16/08/14
<class 'str'>
16/08/14
<class 'str'>
17/08/14
<class 'str'>
17/08/14
<class 'str'>
18/08/14
<class 'str'>
23/08/14
<class 'str'>
23/08/14
<class 'str'>
23/08/14
<class 'str'>
23/08/14
<class 'str'>
23/08/14
<class 'str'>
23/08/14
<class 'str'>
24/08/14
<class 'str'>
24/08/14
<class 'str'>
24/08/14
<class 'str'>
25/08/14
<class 'str'>
30/08/14
<class 'str'>
30/08/14
<class 'str'>
30/08/14
<class 'str'>
30/08/14
<class 'str'>
30/08/14
<class 'str'>
30/08/14
<class 'str'>
30/08/14
<class 'str'>
31/08/14
<class 'str'>
31/08/14
<class 'str'>
31/08/14
<class 'str'>
13/09/14
<class 'str'>
13/09/14
<class 'str'>
13/09/14
<class 'str'>
13/09/14
<class 'str'>
13/09/14
<class 'str'>
13/09/14
<class 'str'>
13/09/14
<class 'str'>
13/09/14
<class 'str'>
14/09/14
<class 'str'>
15/09/14
<class 'str'>
20/09/14
<class 'str'>
20/09/14
<class 'str'>
20/09/14
<class 'str'>
20/09/14
<class 'str'>
20/09/14
<class 'str'>
20/09/14
<class 'str'>
21/09/14
<class 'str'>
21/09/14
<class 'str'>
21/09/14
<class 'str'>
21/09/14
<class 'str'>
27/09/14
<class 'str'>
27/09/14
<class 'str'>
27/09/14
<class 'str'>
27/09/14
<class 'str'>
27/09/14
<class 'str'>
27/09/14
<class 'str'>
27/09/14
<class 'str'>
27/09/14
<class 'str'>
28/09/14
<class 'str'>
29/09/14
<class 'str'>
04/10/14
<class 'str'>
04/10/14
<class 'str'>
04/10/14
<class 'str'>
04/10/14
<class 'str'>
04/10/14
<class 'str'>
04/10/14
<class 'str'>
05/10/14
<class 'str'>
05/10/14
<class 'str'>
05/10/14
<class 'str'>
05/10/14
<class 'str'>
18/10/14
<class 'str'>
18/10/14
<class 'str'>
18/10/14
<class 'str'>
18/10/14
<class 'str'>
18/10/14
<class 'str'>
18/10/14
<class 'str'>
18/10/14
<class 'str'>
19/10/14
<class 'str'>
19/10/14
<class 'str'>
20/10/14
<class 'str'>
25/10/14
<class 'str'>
25/10/14
<class 'str'>
25/10/14
<class 'str'>
25/10/14
<class 'str'>
25/10/14
<class 'str'>
25/10/14
<class 'str'>
26/10/14
<class 'str'>
26/10/14
<class 'str'>
26/10/14
<class 'str'>
27/10/14
<class 'str'>
01/11/14
<class 'str'>
01/11/14
<class 'str'>
01/11/14
<class 'str'>
01/11/14
<class 'str'>
01/11/14
<class 'str'>
01/11/14
<class 'str'>
01/11/14
<class 'str'>
02/11/14
<class 'str'>
02/11/14
<class 'str'>
03/11/14
<class 'str'>
08/11/14
<class 'str'>
08/11/14
<class 'str'>
08/11/14
<class 'str'>
08/11/14
<class 'str'>
08/11/14
<class 'str'>
08/11/14
<class 'str'>
09/11/14
<class 'str'>
09/11/14
<class 'str'>
09/11/14
<class 'str'>
09/11/14
<class 'str'>
22/11/14
<class 'str'>
22/11/14
<class 'str'>
22/11/14
<class 'str'>
22/11/14
<class 'str'>
22/11/14
<class 'str'>
22/11/14
<class 'str'>
22/11/14
<class 'str'>
23/11/14
<class 'str'>
23/11/14
<class 'str'>
24/11/14
<class 'str'>
29/11/14
<class 'str'>
29/11/14
<class 'str'>
29/11/14
<class 'str'>
29/11/14
<class 'str'>
29/11/14
<class 'str'>
29/11/14
<class 'str'>
29/11/14
<class 'str'>
29/11/14
<class 'str'>
30/11/14
<class 'str'>
30/11/14
<class 'str'>
02/12/14
<class 'str'>
02/12/14
<class 'str'>
02/12/14
<class 'str'>
02/12/14
<class 'str'>
02/12/14
<class 'str'>
02/12/14
<class 'str'>
03/12/14
<class 'str'>
03/12/14
<class 'str'>
03/12/14
<class 'str'>
03/12/14
<class 'str'>
06/12/14
<class 'str'>
06/12/14
<class 'str'>
06/12/14
<class 'str'>
06/12/14
<class 'str'>
06/12/14
<class 'str'>
06/12/14
<class 'str'>
06/12/14
<class 'str'>
07/12/14
<class 'str'>
07/12/14
<class 'str'>
08/12/14
<class 'str'>
13/12/14
<class 'str'>
13/12/14
<class 'str'>
13/12/14
<class 'str'>
13/12/14
<class 'str'>
13/12/14
<class 'str'>
13/12/14
<class 'str'>
13/12/14
<class 'str'>
14/12/14
<class 'str'>
14/12/14
<class 'str'>
15/12/14
<class 'str'>
20/12/14
<class 'str'>
20/12/14
<class 'str'>
20/12/14
<class 'str'>
20/12/14
<class 'str'>
20/12/14
<class 'str'>
20/12/14
<class 'str'>
20/12/14
<class 'str'>
21/12/14
<class 'str'>
21/12/14
<class 'str'>
22/12/14
<class 'str'>
26/12/14
<class 'str'>
26/12/14
<class 'str'>
26/12/14
<class 'str'>
26/12/14
<class 'str'>
26/12/14
<class 'str'>
26/12/14
<class 'str'>
26/12/14
<class 'str'>
26/12/14
<class 'str'>
26/12/14
<class 'str'>
26/12/14
<class 'str'>
28/12/14
<class 'str'>
28/12/14
<class 'str'>
28/12/14
<class 'str'>
28/12/14
<class 'str'>
28/12/14
<class 'str'>
28/12/14
<class 'str'>
28/12/14
<class 'str'>
28/12/14
<class 'str'>
28/12/14
<class 'str'>
29/12/14
<class 'str'>
01/01/15
<class 'str'>
01/01/15
<class 'str'>
01/01/15
<class 'str'>
01/01/15
<class 'str'>
01/01/15
<class 'str'>
01/01/15
<class 'str'>
01/01/15
<class 'str'>
01/01/15
<class 'str'>
01/01/15
<class 'str'>
01/01/15
<class 'str'>
10/01/15
<class 'str'>
10/01/15
<class 'str'>
10/01/15
<class 'str'>
10/01/15
<class 'str'>
10/01/15
<class 'str'>
10/01/15
<class 'str'>
10/01/15
<class 'str'>
10/01/15
<class 'str'>
11/01/15
<class 'str'>
11/01/15
<class 'str'>
17/01/15
<class 'str'>
17/01/15
<class 'str'>
17/01/15
<class 'str'>
17/01/15
<class 'str'>
17/01/15
<class 'str'>
17/01/15
<class 'str'>
17/01/15
<class 'str'>
18/01/15
<class 'str'>
18/01/15
<class 'str'>
19/01/15
<class 'str'>
31/01/15
<class 'str'>
31/01/15
<class 'str'>
31/01/15
<class 'str'>
31/01/15
<class 'str'>
31/01/15
<class 'str'>
31/01/15
<class 'str'>
31/01/15
<class 'str'>
31/01/15
<class 'str'>
01/02/15
<class 'str'>
01/02/15
<class 'str'>
07/02/15
<class 'str'>
07/02/15
<class 'str'>
07/02/15
<class 'str'>
07/02/15
<class 'str'>
07/02/15
<class 'str'>
07/02/15
<class 'str'>
07/02/15
<class 'str'>
08/02/15
<class 'str'>
08/02/15
<class 'str'>
08/02/15
<class 'str'>
10/02/15
<class 'str'>
10/02/15
<class 'str'>
10/02/15
<class 'str'>
10/02/15
<class 'str'>
11/02/15
<class 'str'>
11/02/15
<class 'str'>
11/02/15
<class 'str'>
11/02/15
<class 'str'>
11/02/15
<class 'str'>
11/02/15
<class 'str'>
21/02/15
<class 'str'>
21/02/15
<class 'str'>
21/02/15
<class 'str'>
21/02/15
<class 'str'>
21/02/15
<class 'str'>
21/02/15
<class 'str'>
21/02/15
<class 'str'>
22/02/15
<class 'str'>
22/02/15
<class 'str'>
22/02/15
<class 'str'>
28/02/15
<class 'str'>
28/02/15
<class 'str'>
28/02/15
<class 'str'>
28/02/15
<class 'str'>
28/02/15
<class 'str'>
28/02/15
<class 'str'>
01/03/15
<class 'str'>
01/03/15
<class 'str'>
03/03/15
<class 'str'>
03/03/15
<class 'str'>
03/03/15
<class 'str'>
04/03/15
<class 'str'>
04/03/15
<class 'str'>
04/03/15
<class 'str'>
04/03/15
<class 'str'>
04/03/15
<class 'str'>
04/03/15
<class 'str'>
04/03/15
<class 'str'>
07/03/15
<class 'str'>
14/03/15
<class 'str'>
14/03/15
<class 'str'>
14/03/15
<class 'str'>
14/03/15
<class 'str'>
14/03/15
<class 'str'>
14/03/15
<class 'str'>
15/03/15
<class 'str'>
15/03/15
<class 'str'>
15/03/15
<class 'str'>
16/03/15
<class 'str'>
21/03/15
<class 'str'>
21/03/15
<class 'str'>
21/03/15
<class 'str'>
21/03/15
<class 'str'>
21/03/15
<class 'str'>
21/03/15
<class 'str'>
21/03/15
<class 'str'>
22/03/15
<class 'str'>
22/03/15
<class 'str'>
22/03/15
<class 'str'>
04/04/15
<class 'str'>
04/04/15
<class 'str'>
04/04/15
<class 'str'>
04/04/15
<class 'str'>
04/04/15
<class 'str'>
04/04/15
<class 'str'>
04/04/15
<class 'str'>
05/04/15
<class 'str'>
05/04/15
<class 'str'>
06/04/15
<class 'str'>
07/04/15
<class 'str'>
11/04/15
<class 'str'>
11/04/15
<class 'str'>
11/04/15
<class 'str'>
11/04/15
<class 'str'>
11/04/15
<class 'str'>
11/04/15
<class 'str'>
11/04/15
<class 'str'>
12/04/15
<class 'str'>
12/04/15
<class 'str'>
13/04/15
<class 'str'>
18/04/15
<class 'str'>
18/04/15
<class 'str'>
18/04/15
<class 'str'>
18/04/15
<class 'str'>
18/04/15
<class 'str'>
19/04/15
<class 'str'>
19/04/15
<class 'str'>
25/04/15
<class 'str'>
25/04/15
<class 'str'>
25/04/15
<class 'str'>
25/04/15
<class 'str'>
25/04/15
<class 'str'>
25/04/15
<class 'str'>
25/04/15
<class 'str'>
25/04/15
<class 'str'>
26/04/15
<class 'str'>
26/04/15
<class 'str'>
28/04/15
<class 'str'>
29/04/15
<class 'str'>
02/05/15
<class 'str'>
02/05/15
<class 'str'>
02/05/15
<class 'str'>
02/05/15
<class 'str'>
02/05/15
<class 'str'>
02/05/15
<class 'str'>
02/05/15
<class 'str'>
03/05/15
<class 'str'>
03/05/15
<class 'str'>
04/05/15
<class 'str'>
09/05/15
<class 'str'>
09/05/15
<class 'str'>
09/05/15
<class 'str'>
09/05/15
<class 'str'>
09/05/15
<class 'str'>
09/05/15
<class 'str'>
09/05/15
<class 'str'>
10/05/15
<class 'str'>
10/05/15
<class 'str'>
11/05/15
<class 'str'>
16/05/15
<class 'str'>
16/05/15
<class 'str'>
16/05/15
<class 'str'>
16/05/15
<class 'str'>
16/05/15
<class 'str'>
16/05/15
<class 'str'>
16/05/15
<class 'str'>
17/05/15
<class 'str'>
17/05/15
<class 'str'>
18/05/15
<class 'str'>
20/05/15
<class 'str'>
24/05/15
<class 'str'>
24/05/15
<class 'str'>
24/05/15
<class 'str'>
24/05/15
<class 'str'>
24/05/15
<class 'str'>
24/05/15
<class 'str'>
24/05/15
<class 'str'>
24/05/15
<class 'str'>
24/05/15
<class 'str'>
24/05/15
<class 'str'>
17/08/13
<class 'str'>
17/08/13
<class 'str'>
17/08/13
<class 'str'>
17/08/13
<class 'str'>
17/08/13
<class 'str'>
17/08/13
<class 'str'>
17/08/13
<class 'str'>
18/08/13
<class 'str'>
18/08/13
<class 'str'>
19/08/13
<class 'str'>
21/08/13
<class 'str'>
24/08/13
<class 'str'>
24/08/13
<class 'str'>
24/08/13
<class 'str'>
24/08/13
<class 'str'>
24/08/13
<class 'str'>
24/08/13
<class 'str'>
24/08/13
<class 'str'>
25/08/13
<class 'str'>
25/08/13
<class 'str'>
26/08/13
<class 'str'>
31/08/13
<class 'str'>
31/08/13
<class 'str'>
31/08/13
<class 'str'>
31/08/13
<class 'str'>
31/08/13
<class 'str'>
31/08/13
<class 'str'>
01/09/13
<class 'str'>
01/09/13
<class 'str'>
01/09/13
<class 'str'>
14/09/13
<class 'str'>
14/09/13
<class 'str'>
14/09/13
<class 'str'>
14/09/13
<class 'str'>
14/09/13
<class 'str'>
14/09/13
<class 'str'>
14/09/13
<class 'str'>
14/09/13
<class 'str'>
15/09/13
<class 'str'>
16/09/13
<class 'str'>
21/09/13
<class 'str'>
21/09/13
<class 'str'>
21/09/13
<class 'str'>
21/09/13
<class 'str'>
21/09/13
<class 'str'>
21/09/13
<class 'str'>
22/09/13
<class 'str'>
22/09/13
<class 'str'>
22/09/13
<class 'str'>
22/09/13
<class 'str'>
28/09/13
<class 'str'>
28/09/13
<class 'str'>
28/09/13
<class 'str'>
28/09/13
<class 'str'>
28/09/13
<class 'str'>
28/09/13
<class 'str'>
28/09/13
<class 'str'>
29/09/13
<class 'str'>
29/09/13
<class 'str'>
30/09/13
<class 'str'>
05/10/13
<class 'str'>
05/10/13
<class 'str'>
05/10/13
<class 'str'>
05/10/13
<class 'str'>
05/10/13
<class 'str'>
05/10/13
<class 'str'>
06/10/13
<class 'str'>
06/10/13
<class 'str'>
06/10/13
<class 'str'>
06/10/13
<class 'str'>
19/10/13
<class 'str'>
19/10/13
<class 'str'>
19/10/13
<class 'str'>
19/10/13
<class 'str'>
19/10/13
<class 'str'>
19/10/13
<class 'str'>
19/10/13
<class 'str'>
19/10/13
<class 'str'>
20/10/13
<class 'str'>
21/10/13
<class 'str'>
26/10/13
<class 'str'>
26/10/13
<class 'str'>
26/10/13
<class 'str'>
26/10/13
<class 'str'>
26/10/13
<class 'str'>
26/10/13
<class 'str'>
27/10/13
<class 'str'>
27/10/13
<class 'str'>
27/10/13
<class 'str'>
27/10/13
<class 'str'>
02/11/13
<class 'str'>
02/11/13
<class 'str'>
02/11/13
<class 'str'>
02/11/13
<class 'str'>
02/11/13
<class 'str'>
02/11/13
<class 'str'>
02/11/13
<class 'str'>
02/11/13
<class 'str'>
03/11/13
<class 'str'>
03/11/13
<class 'str'>
09/11/13
<class 'str'>
09/11/13
<class 'str'>
09/11/13
<class 'str'>
09/11/13
<class 'str'>
09/11/13
<class 'str'>
09/11/13
<class 'str'>
10/11/13
<class 'str'>
10/11/13
<class 'str'>
10/11/13
<class 'str'>
10/11/13
<class 'str'>
23/11/13
<class 'str'>
23/11/13
<class 'str'>
23/11/13
<class 'str'>
23/11/13
<class 'str'>
23/11/13
<class 'str'>
23/11/13
<class 'str'>
23/11/13
<class 'str'>
24/11/13
<class 'str'>
24/11/13
<class 'str'>
25/11/13
<class 'str'>
30/11/13
<class 'str'>
30/11/13
<class 'str'>
30/11/13
<class 'str'>
30/11/13
<class 'str'>
30/11/13
<class 'str'>
30/11/13
<class 'str'>
01/12/13
<class 'str'>
01/12/13
<class 'str'>
01/12/13
<class 'str'>
01/12/13
<class 'str'>
03/12/13
<class 'str'>
04/12/13
<class 'str'>
04/12/13
<class 'str'>
04/12/13
<class 'str'>
04/12/13
<class 'str'>
04/12/13
<class 'str'>
04/12/13
<class 'str'>
04/12/13
<class 'str'>
04/12/13
<class 'str'>
04/12/13
<class 'str'>
07/12/13
<class 'str'>
07/12/13
<class 'str'>
07/12/13
<class 'str'>
07/12/13
<class 'str'>
07/12/13
<class 'str'>
07/12/13
<class 'str'>
07/12/13
<class 'str'>
08/12/13
<class 'str'>
08/12/13
<class 'str'>
09/12/13
<class 'str'>
14/12/13
<class 'str'>
14/12/13
<class 'str'>
14/12/13
<class 'str'>
14/12/13
<class 'str'>
14/12/13
<class 'str'>
14/12/13
<class 'str'>
14/12/13
<class 'str'>
15/12/13
<class 'str'>
15/12/13
<class 'str'>
15/12/13
<class 'str'>
21/12/13
<class 'str'>
21/12/13
<class 'str'>
21/12/13
<class 'str'>
21/12/13
<class 'str'>
21/12/13
<class 'str'>
21/12/13
<class 'str'>
21/12/13
<class 'str'>
22/12/13
<class 'str'>
22/12/13
<class 'str'>
23/12/13
<class 'str'>
26/12/13
<class 'str'>
26/12/13
<class 'str'>
26/12/13
<class 'str'>
26/12/13
<class 'str'>
26/12/13
<class 'str'>
26/12/13
<class 'str'>
26/12/13
<class 'str'>
26/12/13
<class 'str'>
26/12/13
<class 'str'>
26/12/13
<class 'str'>
28/12/13
<class 'str'>
28/12/13
<class 'str'>
28/12/13
<class 'str'>
28/12/13
<class 'str'>
28/12/13
<class 'str'>
28/12/13
<class 'str'>
29/12/13
<class 'str'>
29/12/13
<class 'str'>
29/12/13
<class 'str'>
29/12/13
<class 'str'>
01/01/14
<class 'str'>
01/01/14
<class 'str'>
01/01/14
<class 'str'>
01/01/14
<class 'str'>
01/01/14
<class 'str'>
01/01/14
<class 'str'>
01/01/14
<class 'str'>
01/01/14
<class 'str'>
01/01/14
<class 'str'>
01/01/14
<class 'str'>
11/01/14
<class 'str'>
11/01/14
<class 'str'>
11/01/14
<class 'str'>
11/01/14
<class 'str'>
11/01/14
<class 'str'>
11/01/14
<class 'str'>
11/01/14
<class 'str'>
12/01/14
<class 'str'>
12/01/14
<class 'str'>
13/01/14
<class 'str'>
18/01/14
<class 'str'>
18/01/14
<class 'str'>
18/01/14
<class 'str'>
18/01/14
<class 'str'>
18/01/14
<class 'str'>
18/01/14
<class 'str'>
18/01/14
<class 'str'>
19/01/14
<class 'str'>
19/01/14
<class 'str'>
20/01/14
<class 'str'>
28/01/14
<class 'str'>
28/01/14
<class 'str'>
28/01/14
<class 'str'>
28/01/14
<class 'str'>
28/01/14
<class 'str'>
28/01/14
<class 'str'>
29/01/14
<class 'str'>
29/01/14
<class 'str'>
29/01/14
<class 'str'>
29/01/14
<class 'str'>
01/02/14
<class 'str'>
01/02/14
<class 'str'>
01/02/14
<class 'str'>
01/02/14
<class 'str'>
01/02/14
<class 'str'>
01/02/14
<class 'str'>
01/02/14
<class 'str'>
02/02/14
<class 'str'>
02/02/14
<class 'str'>
03/02/14
<class 'str'>
08/02/14
<class 'str'>
08/02/14
<class 'str'>
08/02/14
<class 'str'>
08/02/14
<class 'str'>
08/02/14
<class 'str'>
08/02/14
<class 'str'>
08/02/14
<class 'str'>
08/02/14
<class 'str'>
09/02/14
<class 'str'>
09/02/14
<class 'str'>
11/02/14
<class 'str'>
11/02/14
<class 'str'>
11/02/14
<class 'str'>
11/02/14
<class 'str'>
12/02/14
<class 'str'>
12/02/14
<class 'str'>
12/02/14
<class 'str'>
12/02/14
<class 'str'>
22/02/14
<class 'str'>
22/02/14
<class 'str'>
22/02/14
<class 'str'>
22/02/14
<class 'str'>
22/02/14
<class 'str'>
22/02/14
<class 'str'>
22/02/14
<class 'str'>
23/02/14
<class 'str'>
23/02/14
<class 'str'>
23/02/14
<class 'str'>
01/03/14
<class 'str'>
01/03/14
<class 'str'>
01/03/14
<class 'str'>
01/03/14
<class 'str'>
01/03/14
<class 'str'>
02/03/14
<class 'str'>
02/03/14
<class 'str'>
02/03/14
<class 'str'>
08/03/14
<class 'str'>
08/03/14
<class 'str'>
08/03/14
<class 'str'>
08/03/14
<class 'str'>
08/03/14
<class 'str'>
15/03/14
<class 'str'>
15/03/14
<class 'str'>
15/03/14
<class 'str'>
15/03/14
<class 'str'>
15/03/14
<class 'str'>
15/03/14
<class 'str'>
15/03/14
<class 'str'>
15/03/14
<class 'str'>
16/03/14
<class 'str'>
16/03/14
<class 'str'>
22/03/14
<class 'str'>
22/03/14
<class 'str'>
22/03/14
<class 'str'>
22/03/14
<class 'str'>
22/03/14
<class 'str'>
22/03/14
<class 'str'>
22/03/14
<class 'str'>
22/03/14
<class 'str'>
23/03/14
<class 'str'>
23/03/14
<class 'str'>
25/03/14
<class 'str'>
25/03/14
<class 'str'>
25/03/14
<class 'str'>
26/03/14
<class 'str'>
26/03/14
<class 'str'>
29/03/14
<class 'str'>
29/03/14
<class 'str'>
29/03/14
<class 'str'>
29/03/14
<class 'str'>
29/03/14
<class 'str'>
29/03/14
<class 'str'>
29/03/14
<class 'str'>
30/03/14
<class 'str'>
30/03/14
<class 'str'>
31/03/14
<class 'str'>
05/04/14
<class 'str'>
05/04/14
<class 'str'>
05/04/14
<class 'str'>
05/04/14
<class 'str'>
05/04/14
<class 'str'>
05/04/14
<class 'str'>
05/04/14
<class 'str'>
06/04/14
<class 'str'>
06/04/14
<class 'str'>
07/04/14
<class 'str'>
12/04/14
<class 'str'>
12/04/14
<class 'str'>
12/04/14
<class 'str'>
12/04/14
<class 'str'>
12/04/14
<class 'str'>
12/04/14
<class 'str'>
13/04/14
<class 'str'>
13/04/14
<class 'str'>
15/04/14
<class 'str'>
16/04/14
<class 'str'>
16/04/14
<class 'str'>
19/04/14
<class 'str'>
19/04/14
<class 'str'>
19/04/14
<class 'str'>
19/04/14
<class 'str'>
19/04/14
<class 'str'>
19/04/14
<class 'str'>
20/04/14
<class 'str'>
20/04/14
<class 'str'>
20/04/14
<class 'str'>
21/04/14
<class 'str'>
26/04/14
<class 'str'>
26/04/14
<class 'str'>
26/04/14
<class 'str'>
26/04/14
<class 'str'>
26/04/14
<class 'str'>
26/04/14
<class 'str'>
27/04/14
<class 'str'>
27/04/14
<class 'str'>
27/04/14
<class 'str'>
28/04/14
<class 'str'>
03/05/14
<class 'str'>
03/05/14
<class 'str'>
03/05/14
<class 'str'>
03/05/14
<class 'str'>
03/05/14
<class 'str'>
03/05/14
<class 'str'>
03/05/14
<class 'str'>
04/05/14
<class 'str'>
04/05/14
<class 'str'>
05/05/14
<class 'str'>
06/05/14
<class 'str'>
07/05/14
<class 'str'>
07/05/14
<class 'str'>
11/05/14
<class 'str'>
11/05/14
<class 'str'>
11/05/14
<class 'str'>
11/05/14
<class 'str'>
11/05/14
<class 'str'>
11/05/14
<class 'str'>
11/05/14
<class 'str'>
11/05/14
<class 'str'>
11/05/14
<class 'str'>
11/05/14
<class 'str'>
18/08/12
<class 'str'>
18/08/12
<class 'str'>
18/08/12
<class 'str'>
18/08/12
<class 'str'>
18/08/12
<class 'str'>
18/08/12
<class 'str'>
18/08/12
<class 'str'>
19/08/12
<class 'str'>
19/08/12
<class 'str'>
20/08/12
<class 'str'>
22/08/12
<class 'str'>
25/08/12
<class 'str'>
25/08/12
<class 'str'>
25/08/12
<class 'str'>
25/08/12
<class 'str'>
25/08/12
<class 'str'>
25/08/12
<class 'str'>
25/08/12
<class 'str'>
26/08/12
<class 'str'>
26/08/12
<class 'str'>
01/09/12
<class 'str'>
01/09/12
<class 'str'>
01/09/12
<class 'str'>
01/09/12
<class 'str'>
01/09/12
<class 'str'>
01/09/12
<class 'str'>
02/09/12
<class 'str'>
02/09/12
<class 'str'>
02/09/12
<class 'str'>
15/09/12
<class 'str'>
15/09/12
<class 'str'>
15/09/12
<class 'str'>
15/09/12
<class 'str'>
15/09/12
<class 'str'>
15/09/12
<class 'str'>
15/09/12
<class 'str'>
15/09/12
<class 'str'>
16/09/12
<class 'str'>
17/09/12
<class 'str'>
22/09/12
<class 'str'>
22/09/12
<class 'str'>
22/09/12
<class 'str'>
22/09/12
<class 'str'>
22/09/12
<class 'str'>
22/09/12
<class 'str'>
23/09/12
<class 'str'>
23/09/12
<class 'str'>
23/09/12
<class 'str'>
23/09/12
<class 'str'>
29/09/12
<class 'str'>
29/09/12
<class 'str'>
29/09/12
<class 'str'>
29/09/12
<class 'str'>
29/09/12
<class 'str'>
29/09/12
<class 'str'>
29/09/12
<class 'str'>
29/09/12
<class 'str'>
30/09/12
<class 'str'>
01/10/12
<class 'str'>
06/10/12
<class 'str'>
06/10/12
<class 'str'>
06/10/12
<class 'str'>
06/10/12
<class 'str'>
06/10/12
<class 'str'>
06/10/12
<class 'str'>
07/10/12
<class 'str'>
07/10/12
<class 'str'>
07/10/12
<class 'str'>
07/10/12
<class 'str'>
20/10/12
<class 'str'>
20/10/12
<class 'str'>
20/10/12
<class 'str'>
20/10/12
<class 'str'>
20/10/12
<class 'str'>
20/10/12
<class 'str'>
20/10/12
<class 'str'>
20/10/12
<class 'str'>
21/10/12
<class 'str'>
21/10/12
<class 'str'>
27/10/12
<class 'str'>
27/10/12
<class 'str'>
27/10/12
<class 'str'>
27/10/12
<class 'str'>
27/10/12
<class 'str'>
27/10/12
<class 'str'>
28/10/12
<class 'str'>
28/10/12
<class 'str'>
28/10/12
<class 'str'>
28/10/12
<class 'str'>
03/11/12
<class 'str'>
03/11/12
<class 'str'>
03/11/12
<class 'str'>
03/11/12
<class 'str'>
03/11/12
<class 'str'>
03/11/12
<class 'str'>
03/11/12
<class 'str'>
04/11/12
<class 'str'>
04/11/12
<class 'str'>
05/11/12
<class 'str'>
10/11/12
<class 'str'>
10/11/12
<class 'str'>
10/11/12
<class 'str'>
10/11/12
<class 'str'>
10/11/12
<class 'str'>
10/11/12
<class 'str'>
10/11/12
<class 'str'>
11/11/12
<class 'str'>
11/11/12
<class 'str'>
11/11/12

In [333]:
# print(raw_data_1.shape)
print(raw_data_2.shape)
print(raw_data_3.shape)
# raw_data_4.columns[raw_data_3.columns==raw_data_4.columns[:-3]]
# print(raw_data_3.columns)
# print(raw_data_4.columns)

# print(raw_data_4.columns[:-3])
print(raw_data_4.shape)
print(raw_data_5.shape)
print(raw_data_6.shape)
print(raw_data_7.shape)
print(raw_data_8.shape)

(380, 65)
(380, 65)
(380, 68)
(380, 68)
(380, 74)
(380, 71)
(380, 71)

In [334]:
columns_req = ['Date','HomeTeam','AwayTeam','FTHG','FTAG','FTR']
# playing_statistics_1=raw_data_1[columns_req]
playing_statistics_2=raw_data_2[columns_req]
playing_statistics_3=raw_data_3[columns_req]
playing_statistics_4=raw_data_4[columns_req]
playing_statistics_5=raw_data_5[columns_req]
playing_statistics_6=raw_data_6[columns_req]
playing_statistics_7=raw_data_7[columns_req]
playing_statistics_8=raw_data_8[columns_req]

In [335]:
playing_statistics_3.head()
# print(playing_statistics_1.shape)

       Date     HomeTeam     AwayTeam  FTHG  FTAG FTR
0  08/08/15  Bournemouth  Aston Villa     0     1   A
1  08/08/15      Chelsea      Swansea     2     2   D
2  08/08/15      Everton      Watford     2     2   D
3  08/08/15    Leicester   Sunderland     4     2   H
4  08/08/15   Man United    Tottenham     1     0   H

In [336]:
def get_goals_scored(playing_stat):
    print("get_goals_scored")
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        print("check {} \n".format(i))
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        HTGS = playing_stat.iloc[i]['FTHG']
        ATGS = playing_stat.iloc[i]['FTAG']
        teams[playing_stat.iloc[i].HomeTeam].append(HTGS)
        teams[playing_stat.iloc[i].AwayTeam].append(ATGS)
        
#     for i in teams.keys():
#         print("check",len(teams[i]))
#         print(teams[i])
#         if len(teams[i])==31:
#             teams[i]=teams[i][:-1]
#             print("check",len(teams[i]))
#     print("teams",len(teams["Arsenal"]))
#     print(teams)
    # Create a dataframe for goals scored where rows are teams and cols are matchweek.
    GoalsScored = pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T
    GoalsScored[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,39):
        GoalsScored[i] = GoalsScored[i] + GoalsScored[i-1]
    return GoalsScored



# Gets the goals conceded agg arranged by teams and matchweek
def get_goals_conceded(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        print("check {} \n".format(i))
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        ATGC = playing_stat.iloc[i]['FTHG']
        HTGC = playing_stat.iloc[i]['FTAG']
        teams[playing_stat.iloc[i].HomeTeam].append(HTGC)
        teams[playing_stat.iloc[i].AwayTeam].append(ATGC)
#     print(len(teams.keys))
#     for i in teams.keys():
#         print("check",len(teams[i]))
#         print(teams[i])
#         if len(teams[i])==31:
#             teams[i]=teams[i][:-1]
#             print("check",len(teams[i]))
#     print("teams",len(teams["Arsenal"]))
#     print(teams)
    
    # Create a dataframe for goals scored where rows are teams and cols are matchweek.
    GoalsConceded = pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T
    GoalsConceded[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,len(teams["Arsenal"])+1):
        GoalsConceded[i] = GoalsConceded[i] + GoalsConceded[i-1]
    return GoalsConceded

def get_gss(playing_stat):
    GC = get_goals_conceded(playing_stat)
    GS = get_goals_scored(playing_stat)
   
    j = 0
    HTGS = []
    ATGS = []
    HTGC = []
    ATGC = []

    for i in range(380):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        HTGS.append(GS.loc[ht][j])
        ATGS.append(GS.loc[at][j])
        HTGC.append(GC.loc[ht][j])
        ATGC.append(GC.loc[at][j])
        
        if ((i + 1)% 10) == 0:
            j = j + 1
    
#     print("check line 87")
#     print(playing_stat.shape,len(HTGS))
    
    playing_stat['HTGS'] = HTGS
    playing_stat['ATGS'] = ATGS
    playing_stat['HTGC'] = HTGC
    playing_stat['ATGC'] = ATGC
    
    return playing_stat


# Apply to each dataset
# playing_statistics_1 = get_gss(playing_statistics_1)
# print(playing_statistics_1.head())
playing_statistics_2 = get_gss(playing_statistics_2)
playing_statistics_3 = get_gss(playing_statistics_3)
playing_statistics_4 = get_gss(playing_statistics_4)
playing_statistics_5 = get_gss(playing_statistics_5)
playing_statistics_6 = get_gss(playing_statistics_6)
playing_statistics_7 = get_gss(playing_statistics_7)
playing_statistics_8 = get_gss(playing_statistics_8)

check Arsenal

check Bournemouth

check Burnley

check Chelsea

check Crystal Palace

check Everton

check Hull

check Leicester

check Liverpool

check Man City

check Man United

check Middlesbrough

check Southampton

check Stoke

check Sunderland

check Swansea

check Tottenham

check Watford

check West Brom

check West Ham

get_goals_scored
check Arsenal

check Bournemouth

check Burnley

check Chelsea

check Crystal Palace

check Everton

check Hull

check Leicester

check Liverpool

check Man City

check Man United

check Middlesbrough

check Southampton

check Stoke

check Sunderland

check Swansea

check Tottenham

check Watford

check West Brom

check West Ham

C:\Users\krishna\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:90: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\krishna\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:91: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\krishna\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:92: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\krishna\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:93: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

check Arsenal

check Aston Villa

check Bournemouth

check Chelsea

check Crystal Palace

check Everton

check Leicester

check Liverpool

check Man City

check Man United

check Newcastle

check Norwich

check Southampton

check Stoke

check Sunderland

check Swansea

check Tottenham

check Watford

check West Brom

check West Ham

get_goals_scored
check Arsenal

check Aston Villa

check Bournemouth

check Chelsea

check Crystal Palace

check Everton

check Leicester

check Liverpool

check Man City

check Man United

check Newcastle

check Norwich

check Southampton

check Stoke

check Sunderland

check Swansea

check Tottenham

check Watford

check West Brom

check West Ham

check Arsenal

check Aston Villa

check Burnley

check Chelsea

check Crystal Palace

check Everton

check Hull

check Leicester

check Liverpool

check Man City

check Man United

check Newcastle

check QPR

check Southampton

check Stoke

check Sunderland

check Swansea

check Tottenham

check West Brom

check West Ham

get_goals_scored
check Arsenal

check Aston Villa

check Burnley

check Chelsea

check Crystal Palace

check Everton

check Hull

check Leicester

check Liverpool

check Man City

check Man United

check Newcastle

check QPR

check Southampton

check Stoke

check Sunderland

check Swansea

check Tottenham

check West Brom

check West Ham

check Arsenal

check Aston Villa

check Cardiff

check Chelsea

check Crystal Palace

check Everton

check Fulham

check Hull

check Liverpool

check Man City

check Man United

check Newcastle

check Norwich

check Southampton

check Stoke

check Sunderland

check Swansea

check Tottenham

check West Brom

check West Ham

get_goals_scored
check Arsenal

check Aston Villa

check Cardiff

check Chelsea

check Crystal Palace

check Everton

check Fulham

check Hull

check Liverpool

check Man City

check Man United

check Newcastle

check Norwich

check Southampton

check Stoke

check Sunderland

check Swansea

check Tottenham

check West Brom

check West Ham

check Arsenal

check Aston Villa

check Chelsea

check Everton

check Fulham

check Liverpool

check Man City

check Man United

check Newcastle

check Norwich

check QPR

check Reading

check Southampton

check Stoke

check Sunderland

check Swansea

check Tottenham

check West Brom

check West Ham

check Wigan

get_goals_scored
check Arsenal

check Aston Villa

check Chelsea

check Everton

check Fulham

check Liverpool

check Man City

check Man United

check Newcastle

check Norwich

check QPR

check Reading

check Southampton

check Stoke

check Sunderland

check Swansea

check Tottenham

check West Brom

check West Ham

check Wigan

check Arsenal

check Aston Villa

check Blackburn

check Bolton

check Chelsea

check Everton

check Fulham

check Liverpool

check Man City

check Man United

check Newcastle

check Norwich

check QPR

check Stoke

check Sunderland

check Swansea

check Tottenham

check West Brom

check Wigan

check Wolves

get_goals_scored
check Arsenal

check Aston Villa

check Blackburn

check Bolton

check Chelsea

check Everton

check Fulham

check Liverpool

check Man City

check Man United

check Newcastle

check Norwich

check QPR

check Stoke

check Sunderland

check Swansea

check Tottenham

check West Brom

check Wigan

check Wolves

check Arsenal

check Aston Villa

check Birmingham

check Blackburn

check Blackpool

check Bolton

check Chelsea

check Everton

check Fulham

check Liverpool

check Man City

check Man United

check Newcastle

check Stoke

check Sunderland

check Tottenham

check West Brom

check West Ham

check Wigan

check Wolves

get_goals_scored
check Arsenal

check Aston Villa

check Birmingham

check Blackburn

check Blackpool

check Bolton

check Chelsea

check Everton

check Fulham

check Liverpool

check Man City

check Man United

check Newcastle

check Stoke

check Sunderland

check Tottenham

check West Brom

check West Ham

check Wigan

check Wolves

In [337]:
playing_statistics_3.head()

       Date     HomeTeam     AwayTeam  FTHG  FTAG FTR  HTGS  ATGS  HTGC  ATGC
0  08/08/15  Bournemouth  Aston Villa     0     1   A     0     0     0     0
1  08/08/15      Chelsea      Swansea     2     2   D     0     0     0     0
2  08/08/15      Everton      Watford     2     2   D     0     0     0     0
3  08/08/15    Leicester   Sunderland     4     2   H     0     0     0     0
4  08/08/15   Man United    Tottenham     1     0   H     0     0     0     0

In [338]:
def get_points(result):
    if result == 'W':
        return 3
    elif result == 'D':
        return 1
    else:
        return 0
    

def get_cuml_points(matchres):
    matchres_points = matchres.applymap(get_points)
    for i in range(2,31):
        matchres_points[i] = matchres_points[i] + matchres_points[i-1]
        
    matchres_points.insert(column =0, loc = 0, value = [0*i for i in range(20)])
    return matchres_points


def get_matchres(playing_stat):
    print("here")
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []

    # the value corresponding to keys is a list containing the match result
    for i in range(len(playing_stat)):
        if playing_stat.iloc[i].FTR == 'H':
            teams[playing_stat.iloc[i].HomeTeam].append('W')
            teams[playing_stat.iloc[i].AwayTeam].append('L')
        elif playing_stat.iloc[i].FTR == 'A':
            teams[playing_stat.iloc[i].AwayTeam].append('W')
            teams[playing_stat.iloc[i].HomeTeam].append('L')
        else:
            teams[playing_stat.iloc[i].AwayTeam].append('D')
            teams[playing_stat.iloc[i].HomeTeam].append('D')
    
#     for i in teams.keys():
#         print("check",len(teams[i]))
#         print(teams[i])
#         if len(teams[i])>=31:
#             teams[i]=teams[i][:30]
#             print("check",len(teams[i]))
#     print("teams",len(teams["Arsenal"]))
#     print(teams)
            
    return pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T

def get_agg_points(playing_stat):
    matchres = get_matchres(playing_stat)
    cum_pts = get_cuml_points(matchres)
    HTP = []
    ATP = []
    j = 0
    for i in range(380):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        HTP.append(cum_pts.loc[ht][j])
        ATP.append(cum_pts.loc[at][j])

        if ((i + 1)% 10) == 0:
            j = j + 1
            
    playing_stat['HTP'] = HTP
    playing_stat['ATP'] = ATP
    return playing_stat
    
# Apply to each dataset
# playing_statistics_1 = get_agg_points(playing_statistics_1)
print("playing_statistics_2")
playing_statistics_2 = get_agg_points(playing_statistics_2)
print("playing_statistics_3")
playing_statistics_3 = get_agg_points(playing_statistics_3)
playing_statistics_3 = get_agg_points(playing_statistics_4)
playing_statistics_4 = get_agg_points(playing_statistics_5)
playing_statistics_5 = get_agg_points(playing_statistics_6)
playing_statistics_7 = get_agg_points(playing_statistics_7)
playing_statistics_8 = get_agg_points(playing_statistics_8)

playing_statistics_2
here

C:\Users\krishna\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\krishna\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

playing_statistics_3
here
here
here
here
here
here

In [339]:
playing_statistics_3

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTGS,ATGS,HTGC,ATGC,HTP,ATP
0,2014-08-16,Arsenal,Crystal Palace,2,1,H,0,0,0,0,0,0
1,2014-08-16,Leicester,Everton,2,2,D,0,0,0,0,0,0
2,2014-08-16,Man United,Swansea,1,2,A,0,0,0,0,0,0
3,2014-08-16,QPR,Hull,0,1,A,0,0,0,0,0,0
4,2014-08-16,Stoke,Aston Villa,0,1,A,0,0,0,0,0,0
5,2014-08-16,West Brom,Sunderland,2,2,D,0,0,0,0,0,0
6,2014-08-16,West Ham,Tottenham,0,1,A,0,0,0,0,0,0
7,2014-08-17,Liverpool,Southampton,2,1,H,0,0,0,0,0,0
8,2014-08-17,Newcastle,Man City,0,2,A,0,0,0,0,0,0
9,2014-08-18,Burnley,Chelsea,1,3,A,0,0,0,0,0,0
10,2014-08-23,Aston Villa,Newcastle,0,0,D,1,0,0,2,3,0
11,2014-08-23,Chelsea,Leicester,2,0,H,3,2,1,2,3,1
12,2014-08-23,Crystal Palace,West Ham,1,3,A,1,0,2,1,0,0
13,2014-08-23,Everton,Arsenal,2,2,D,2,2,2,1,1,3
14,2014-08-23,Southampton,West Brom,0,0,D,1,2,2,2,0,1
15,2014-08-23,Swansea,Burnley,1,0,H,2,1,1,3,3,0
16,2014-08-24,Hull,Stoke,1,1,D,1,0,0,1,3,0
17,2014-08-24,Sunderland,Man United,1,1,D,2,1,2,2,1,0
18,2014-08-24,Tottenham,QPR,4,0,H,1,0,0,1,3,0
19,2014-08-25,Man City,Liverpool,3,1,H,2,2,0,1,3,3
20,2014-08-30,Burnley,Man United,0,0,D,1,2,4,3,0,1
21,2014-08-30,Everton,Chelsea,3,6,A,4,5,4,1,2,6
22,2014-08-30,Man City,Stoke,0,1,A,5,1,1,2,6,1
23,2014-08-30,Newcastle,Crystal Palace,3,3,D,0,2,2,5,1,0
24,2014-08-30,QPR,Sunderland,1,0,H,0,3,5,3,0,2
25,2014-08-30,Swansea,West Brom,3,0,H,3,2,1,2,6,2
26,2014-08-30,West Ham,Southampton,1,3,A,3,1,2,2,3,1
27,2014-08-31,Aston Villa,Hull,2,1,H,1,2,0,1,4,4
28,2014-08-31,Leicester,Arsenal,1,1,D,2,4,4,3,1,4
29,2014-08-31,Tottenham,Liverpool,0,3,A,5,3,0,4,6,3
...,...,...,...,...,...,...,...,...,...,...,...,...
350,2015-05-09,Crystal Palace,Man United,1,2,A,42,59,48,35,0,0
351,2015-05-09,Everton,Sunderland,0,2,A,46,30,46,50,0,3
352,2015-05-09,Hull,Burnley,0,1,A,33,26,48,53,0,0
353,2015-05-09,Leicester,Southampton,2,0,H,39,48,54,28,3,0
354,2015-05-09,Newcastle,West Brom,1,1,D,36,33,60,46,0,3
355,2015-05-09,Stoke,Tottenham,3,0,H,39,55,44,50,0,0
356,2015-05-10,Chelsea,Liverpool,1,1,D,69,49,27,38,3,3
357,2015-05-10,Man City,QPR,6,0,H,71,39,36,61,3,0
358,2015-05-11,Arsenal,Swansea,0,1,A,66,43,34,44,0,3
359,2015-05-16,Burnley,Stoke,0,0,D,26,39,53,44,0,0
360,2015-05-16,Liverpool,Crystal Palace,1,3,A,50,43,39,50,1,0
361,2015-05-16,QPR,Newcastle,2,1,H,39,37,67,61,0,1
362,2015-05-16,Southampton,Aston Villa,6,1,H,48,30,30,50,0,3
363,2015-05-16,Sunderland,Leicester,0,0,D,30,41,50,54,1,3
364,2015-05-16,Tottenham,Hull,2,0,H,55,33,53,49,0,0
365,2015-05-16,West Ham,Everton,1,2,A,43,46,43,48,0,0
366,2015-05-17,Man United,Arsenal,1,1,D,61,67,36,35,3,1
367,2015-05-17,Swansea,Man City,2,4,A,44,77,44,36,3,3
368,2015-05-18,West Brom,Chelsea,3,0,H,34,70,47,28,1,1
369,2015-05-20,Arsenal,Sunderland,0,0,D,67,30,35,50,1,1
370,2015-05-24,Arsenal,West Brom,4,1,H,67,37,35,47,1,3
371,2015-05-24,Aston Villa,Burnley,0,1,A,31,27,56,53,0,1
372,2015-05-24,Chelsea,Sunderland,3,1,H,70,30,31,50,0,1
373,2015-05-24,Crystal Palace,Swansea,1,0,H,46,46,51,48,3,0
374,2015-05-24,Everton,Tottenham,0,1,A,48,57,49,53,3,3
375,2015-05-24,Hull,Man United,0,0,D,33,62,51,37,0,1
376,2015-05-24,Leicester,QPR,5,1,H,41,41,54,68,1,3
377,2015-05-24,Man City,Southampton,2,0,H,81,54,38,31,3,3
378,2015-05-24,Newcastle,West Ham,2,0,H,38,44,63,45,0,0
379,2015-05-24,Stoke,Liverpool,6,1,H,42,51,44,42,1,0

In [340]:
def get_form(playing_stat,num):
    form = get_matchres(playing_stat)
    form_final = form.copy()
    for i in range(num,39):
        form_final[i] = ''
        j = 0
        while j < num:
            form_final[i] += form[i-j]
            j += 1           
    return form_final

def add_form(playing_stat,num):
    form = get_form(playing_stat,num)
    h = ['M' for i in range(num * 10)]  # since form is not available for n MW (n*10)
    a = ['M' for i in range(num * 10)]
    
    j = num
    for i in range((num*10),380):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        
        past = form.loc[ht][j]               # get past n results
        h.append(past[num-1])                    # 0 index is most recent
        
        past = form.loc[at][j]               # get past n results.
        a.append(past[num-1])                   # 0 index is most recent
        
        if ((i + 1)% 10) == 0:
            j = j + 1
    
    playing_stat['HM' + str(num)] = h[:playing_stat.shape[0]]                 
    playing_stat['AM' + str(num)] = a[:playing_stat.shape[0]]

    
    return playing_stat


def add_form_df(playing_statistics):
    playing_statistics = add_form(playing_statistics,1)
    playing_statistics = add_form(playing_statistics,2)
    playing_statistics = add_form(playing_statistics,3)
    playing_statistics = add_form(playing_statistics,4)
    playing_statistics = add_form(playing_statistics,5)
    return playing_statistics    
    
# Make changes to df
# playing_statistics_1 = add_form_df(playing_statistics_1)
playing_statistics_2 = add_form_df(playing_statistics_2)
playing_statistics_3 = add_form_df(playing_statistics_3)
playing_statistics_4 = add_form_df(playing_statistics_4)
playing_statistics_5 = add_form_df(playing_statistics_5)
playing_statistics_6 = add_form_df(playing_statistics_6)
playing_statistics_7 = add_form_df(playing_statistics_7)
playing_statistics_8 = add_form_df(playing_statistics_8)

here

C:\Users\krishna\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\krishna\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

here
here
here
here
here
here
here
here
here
here
here
here
here
here
here
here
here
here
here
here
here
here
here
here
here
here
here
here
here
here
here
here
here
here

In [341]:
playing_statistics_3

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTGS,ATGS,HTGC,ATGC,...,HM1,AM1,HM2,AM2,HM3,AM3,HM4,AM4,HM5,AM5
0,2014-08-16,Arsenal,Crystal Palace,2,1,H,0,0,0,0,...,M,M,M,M,M,M,M,M,M,M
1,2014-08-16,Leicester,Everton,2,2,D,0,0,0,0,...,M,M,M,M,M,M,M,M,M,M
2,2014-08-16,Man United,Swansea,1,2,A,0,0,0,0,...,M,M,M,M,M,M,M,M,M,M
3,2014-08-16,QPR,Hull,0,1,A,0,0,0,0,...,M,M,M,M,M,M,M,M,M,M
4,2014-08-16,Stoke,Aston Villa,0,1,A,0,0,0,0,...,M,M,M,M,M,M,M,M,M,M
5,2014-08-16,West Brom,Sunderland,2,2,D,0,0,0,0,...,M,M,M,M,M,M,M,M,M,M
6,2014-08-16,West Ham,Tottenham,0,1,A,0,0,0,0,...,M,M,M,M,M,M,M,M,M,M
7,2014-08-17,Liverpool,Southampton,2,1,H,0,0,0,0,...,M,M,M,M,M,M,M,M,M,M
8,2014-08-17,Newcastle,Man City,0,2,A,0,0,0,0,...,M,M,M,M,M,M,M,M,M,M
9,2014-08-18,Burnley,Chelsea,1,3,A,0,0,0,0,...,M,M,M,M,M,M,M,M,M,M
10,2014-08-23,Aston Villa,Newcastle,0,0,D,1,0,0,2,...,W,L,M,M,M,M,M,M,M,M
11,2014-08-23,Chelsea,Leicester,2,0,H,3,2,1,2,...,W,D,M,M,M,M,M,M,M,M
12,2014-08-23,Crystal Palace,West Ham,1,3,A,1,0,2,1,...,L,L,M,M,M,M,M,M,M,M
13,2014-08-23,Everton,Arsenal,2,2,D,2,2,2,1,...,D,W,M,M,M,M,M,M,M,M
14,2014-08-23,Southampton,West Brom,0,0,D,1,2,2,2,...,L,D,M,M,M,M,M,M,M,M
15,2014-08-23,Swansea,Burnley,1,0,H,2,1,1,3,...,W,L,M,M,M,M,M,M,M,M
16,2014-08-24,Hull,Stoke,1,1,D,1,0,0,1,...,W,L,M,M,M,M,M,M,M,M
17,2014-08-24,Sunderland,Man United,1,1,D,2,1,2,2,...,D,L,M,M,M,M,M,M,M,M
18,2014-08-24,Tottenham,QPR,4,0,H,1,0,0,1,...,W,L,M,M,M,M,M,M,M,M
19,2014-08-25,Man City,Liverpool,3,1,H,2,2,0,1,...,W,W,M,M,M,M,M,M,M,M
20,2014-08-30,Burnley,Man United,0,0,D,1,2,4,3,...,L,D,L,L,M,M,M,M,M,M
21,2014-08-30,Everton,Chelsea,3,6,A,4,5,4,1,...,D,W,D,W,M,M,M,M,M,M
22,2014-08-30,Man City,Stoke,0,1,A,5,1,1,2,...,W,D,W,L,M,M,M,M,M,M
23,2014-08-30,Newcastle,Crystal Palace,3,3,D,0,2,2,5,...,D,L,L,L,M,M,M,M,M,M
24,2014-08-30,QPR,Sunderland,1,0,H,0,3,5,3,...,L,D,L,D,M,M,M,M,M,M
25,2014-08-30,Swansea,West Brom,3,0,H,3,2,1,2,...,W,D,W,D,M,M,M,M,M,M
26,2014-08-30,West Ham,Southampton,1,3,A,3,1,2,2,...,W,D,L,L,M,M,M,M,M,M
27,2014-08-31,Aston Villa,Hull,2,1,H,1,2,0,1,...,D,D,W,W,M,M,M,M,M,M
28,2014-08-31,Leicester,Arsenal,1,1,D,2,4,4,3,...,L,D,D,W,M,M,M,M,M,M
29,2014-08-31,Tottenham,Liverpool,0,3,A,5,3,0,4,...,W,L,W,W,M,M,M,M,M,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,2015-05-09,Crystal Palace,Man United,1,2,A,42,59,48,35,...,L,L,L,L,L,L,W,W,W,W
351,2015-05-09,Everton,Sunderland,0,2,A,46,30,46,50,...,L,W,W,W,W,D,D,L,W,W
352,2015-05-09,Hull,Burnley,0,1,A,33,26,48,53,...,L,L,W,L,W,L,L,L,L,D
353,2015-05-09,Leicester,Southampton,2,0,H,39,48,54,28,...,W,L,L,D,W,L,W,W,W,L
354,2015-05-09,Newcastle,West Brom,1,1,D,36,33,60,46,...,L,W,L,D,L,W,L,L,L,L
355,2015-05-09,Stoke,Tottenham,3,0,H,39,55,44,50,...,L,L,D,D,W,W,D,L,L,D
356,2015-05-10,Chelsea,Liverpool,1,1,D,69,49,27,38,...,W,W,W,L,D,D,W,W,W,L
357,2015-05-10,Man City,QPR,6,0,H,71,39,36,61,...,W,L,W,D,W,L,L,D,L,W
358,2015-05-11,Arsenal,Swansea,0,1,A,66,43,34,44,...,L,W,W,W,D,L,W,D,W,W
359,2015-05-16,Burnley,Stoke,0,0,D,26,39,53,44,...,L,L,L,D,L,W,L,D,D,L
360,2015-05-16,Liverpool,Crystal Palace,1,3,A,50,43,39,50,...,D,L,W,L,L,L,D,L,W,W
361,2015-05-16,QPR,Newcastle,2,1,H,39,37,67,61,...,L,D,L,L,D,L,L,L,D,L
362,2015-05-16,Southampton,Aston Villa,6,1,H,48,30,30,50,...,L,W,L,W,D,L,L,W,W,D
363,2015-05-16,Sunderland,Leicester,0,0,D,30,41,50,54,...,D,W,W,W,W,L,D,W,L,W
364,2015-05-16,Tottenham,Hull,2,0,H,55,33,53,49,...,L,L,L,L,D,W,W,W,L,L
365,2015-05-16,West Ham,Everton,1,2,A,43,46,43,48,...,L,L,W,L,D,W,L,W,D,D
366,2015-05-17,Man United,Arsenal,1,1,D,61,67,36,35,...,W,D,L,L,L,W,L,D,W,W
367,2015-05-17,Swansea,Man City,2,4,A,44,77,44,36,...,W,W,W,W,W,W,L,W,D,L
368,2015-05-18,West Brom,Chelsea,3,0,H,34,70,47,28,...,D,D,W,W,D,W,W,D,L,W
369,2015-05-20,Arsenal,Sunderland,0,0,D,67,30,35,50,...,D,D,L,W,W,W,D,D,W,L
370,2015-05-24,Arsenal,West Brom,4,1,H,67,37,35,47,...,D,W,D,D,L,W,W,D,D,W
371,2015-05-24,Aston Villa,Burnley,0,1,A,31,27,56,53,...,L,D,W,W,W,L,L,L,W,L
372,2015-05-24,Chelsea,Sunderland,3,1,H,70,30,31,50,...,L,D,D,D,W,W,W,W,D,D
373,2015-05-24,Crystal Palace,Swansea,1,0,H,46,46,51,48,...,W,L,L,W,L,W,L,W,L,L
374,2015-05-24,Everton,Tottenham,0,1,A,48,57,49,53,...,W,W,L,L,L,L,W,D,W,W
375,2015-05-24,Hull,Man United,0,0,D,33,62,51,37,...,L,D,L,W,L,L,W,L,W,L
376,2015-05-24,Leicester,QPR,5,1,H,41,41,54,68,...,D,W,W,L,W,L,L,D,W,L
377,2015-05-24,Man City,Southampton,2,0,H,81,54,38,31,...,W,W,W,L,W,L,W,D,W,L
378,2015-05-24,Newcastle,West Ham,2,0,H,38,44,63,45,...,L,L,D,L,L,W,L,D,L,L
379,2015-05-24,Stoke,Liverpool,6,1,H,42,51,44,42,...,D,L,W,D,L,W,D,L,W,D

In [342]:
cols = ['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTGS', 'ATGS', 'HTGC', 'ATGC', 'HTP', 'ATP', 'HM1', 'HM2', 'HM3',
        'HM4', 'HM5', 'AM1', 'AM2', 'AM3', 'AM4', 'AM5' ]

# print(playing_statistics_2.columns)

# playing_statistics_1 = playing_statistics_1[cols]
playing_statistics_2 = playing_statistics_2[cols]
playing_statistics_3 = playing_statistics_3[cols]
playing_statistics_4 = playing_statistics_4[cols]
playing_statistics_5 = playing_statistics_5[cols]
playing_statistics_6 = playing_statistics_6[cols]
playing_statistics_7 = playing_statistics_7[cols]
playing_statistics_8 = playing_statistics_8[cols]

In [343]:
Standings = pd.read_csv(loc + "eplStandings.csv")
Standings.set_index(['Team'], inplace=True)
Standings = Standings.fillna(18)

def get_last(playing_stat, Standings, year):
    HomeTeamLP = []
    AwayTeamLP = []
    for i in range(380):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        HomeTeamLP.append(Standings.loc[ht][year])
        AwayTeamLP.append(Standings.loc[at][year])
    playing_stat['HomeTeamLP'] = HomeTeamLP
    playing_stat['AwayTeamLP'] = AwayTeamLP
    return playing_stat

# playing_statistics_1 = get_last(playing_statistics_1, Standings, 0)
playing_statistics_2 = get_last(playing_statistics_2, Standings, "15")
playing_statistics_3 = get_last(playing_statistics_3, Standings, "14")
playing_statistics_4 = get_last(playing_statistics_3, Standings, "13")
playing_statistics_5 = get_last(playing_statistics_3, Standings, "12")
playing_statistics_6 = get_last(playing_statistics_3, Standings, "11")
playing_statistics_7 = get_last(playing_statistics_3, Standings, "10")
playing_statistics_8 = get_last(playing_statistics_3, Standings, "9")

C:\Users\krishna\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
C:\Users\krishna\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [344]:
playing_statistics_4.head()

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTGS,ATGS,HTGC,ATGC,...,HM3,HM4,HM5,AM1,AM2,AM3,AM4,AM5,HomeTeamLP,AwayTeamLP
0,2014-08-16,Arsenal,Crystal Palace,2,1,H,0,0,0,0,...,M,M,M,M,M,M,M,M,3.0,18.0
1,2014-08-16,Leicester,Everton,2,2,D,0,0,0,0,...,M,M,M,M,M,M,M,M,18.0,8.0
2,2014-08-16,Man United,Swansea,1,2,A,0,0,0,0,...,M,M,M,M,M,M,M,M,2.0,18.0
3,2014-08-16,QPR,Hull,0,1,A,0,0,0,0,...,M,M,M,M,M,M,M,M,18.0,19.0
4,2014-08-16,Stoke,Aston Villa,0,1,A,0,0,0,0,...,M,M,M,M,M,M,M,M,11.0,6.0

In [345]:
def get_mw(playing_stat):
    j = 1
    MatchWeek = []
    for i in range(380):
        MatchWeek.append(j)
        if ((i + 1)% 10) == 0:
            j = j + 1
    playing_stat['MW'] = MatchWeek
    return playing_stat

# playing_statistics_1 = get_mw(playing_statistics_1)
playing_statistics_2 = get_mw(playing_statistics_2)
playing_statistics_3 = get_mw(playing_statistics_3)
playing_statistics_4 = get_mw(playing_statistics_4)
playing_statistics_5 = get_mw(playing_statistics_5)
playing_statistics_6 = get_mw(playing_statistics_6)
playing_statistics_7 = get_mw(playing_statistics_7)
playing_statistics_8 = get_mw(playing_statistics_8)

C:\Users\krishna\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [346]:
playing_stat = pd.concat([playing_statistics_8,
                          playing_statistics_7,
                         playing_statistics_6,
                         playing_statistics_5,
                         playing_statistics_4,
                         playing_statistics_3,
                         playing_statistics_2], ignore_index=True)


# Gets the form points.
def get_form_points(string):
    sum = 0
    for letter in string:
        sum += get_points(letter)
    return sum

playing_stat['HTFormPtsStr'] = playing_stat['HM1'] + playing_stat['HM2'] + playing_stat['HM3'] + playing_stat['HM4'] + playing_stat['HM5']
playing_stat['ATFormPtsStr'] = playing_stat['AM1'] + playing_stat['AM2'] + playing_stat['AM3'] + playing_stat['AM4'] + playing_stat['AM5']

playing_stat['HTFormPts'] = playing_stat['HTFormPtsStr'].apply(get_form_points)
playing_stat['ATFormPts'] = playing_stat['ATFormPtsStr'].apply(get_form_points)

# Identify Win/Loss Streaks if any.
def get_3game_ws(string):
    if string[-3:] == 'WWW':
        return 1
    else:
        return 0
    
def get_5game_ws(string):
    if string == 'WWWWW':
        return 1
    else:
        return 0
    
def get_3game_ls(string):
    if string[-3:] == 'LLL':
        return 1
    else:
        return 0
    
def get_5game_ls(string):
    if string == 'LLLLL':
        return 1
    else:
        return 0
    
playing_stat['HTWinStreak3'] = playing_stat['HTFormPtsStr'].apply(get_3game_ws)
playing_stat['HTWinStreak5'] = playing_stat['HTFormPtsStr'].apply(get_5game_ws)
playing_stat['HTLossStreak3'] = playing_stat['HTFormPtsStr'].apply(get_3game_ls)
playing_stat['HTLossStreak5'] = playing_stat['HTFormPtsStr'].apply(get_5game_ls)

playing_stat['ATWinStreak3'] = playing_stat['ATFormPtsStr'].apply(get_3game_ws)
playing_stat['ATWinStreak5'] = playing_stat['ATFormPtsStr'].apply(get_5game_ws)
playing_stat['ATLossStreak3'] = playing_stat['ATFormPtsStr'].apply(get_3game_ls)
playing_stat['ATLossStreak5'] = playing_stat['ATFormPtsStr'].apply(get_5game_ls)

playing_stat.keys()

Index(['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTGS', 'ATGS',
       'HTGC', 'ATGC', 'HTP', 'ATP', 'HM1', 'HM2', 'HM3', 'HM4', 'HM5', 'AM1',
       'AM2', 'AM3', 'AM4', 'AM5', 'HomeTeamLP', 'AwayTeamLP', 'MW',
       'HTFormPtsStr', 'ATFormPtsStr', 'HTFormPts', 'ATFormPts',
       'HTWinStreak3', 'HTWinStreak5', 'HTLossStreak3', 'HTLossStreak5',
       'ATWinStreak3', 'ATWinStreak5', 'ATLossStreak3', 'ATLossStreak5'],
      dtype='object')

In [347]:
# Get Goal Difference
playing_stat['HTGD'] = playing_stat['HTGS'] - playing_stat['HTGC']
playing_stat['ATGD'] = playing_stat['ATGS'] - playing_stat['ATGC']

# Diff in points
playing_stat['DiffPts'] = playing_stat['HTP'] - playing_stat['ATP']
playing_stat['DiffFormPts'] = playing_stat['HTFormPts'] - playing_stat['ATFormPts']

# Diff in last year positions
playing_stat['DiffLP'] = playing_stat['HomeTeamLP'] - playing_stat['AwayTeamLP']

In [348]:
playing_stat.head()

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTGS,ATGS,HTGC,ATGC,...,HTLossStreak5,ATWinStreak3,ATWinStreak5,ATLossStreak3,ATLossStreak5,HTGD,ATGD,DiffPts,DiffFormPts,DiffLP
0,2014-08-16,Arsenal,Crystal Palace,2,1,H,0,0,0,0,...,0,0,0,0,0,0,0,0,0,-15.0
1,2014-08-16,Leicester,Everton,2,2,D,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10.0
2,2014-08-16,Man United,Swansea,1,2,A,0,0,0,0,...,0,0,0,0,0,0,0,0,0,-16.0
3,2014-08-16,QPR,Hull,0,1,A,0,0,0,0,...,0,0,0,0,0,0,0,0,0,-1.0
4,2014-08-16,Stoke,Aston Villa,0,1,A,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5.0

In [349]:
def only_hw(string):
    if string == 'H':
        return 'H'
    else:
        return 'NH'
    
playing_stat['FTR'] = playing_stat.FTR.apply(only_hw)

In [350]:
playing_stat=playing_stat.drop(["Date","HomeTeam","AwayTeam","HomeTeamLP","AwayTeamLP","HTFormPts","ATFormPts",
                                "FTHG","FTAG","HTFormPtsStr","ATFormPtsStr"],axis=1)
playing_stat.head()

,FTR,HTGS,ATGS,HTGC,ATGC,HTP,ATP,HM1,HM2,HM3,...,HTLossStreak5,ATWinStreak3,ATWinStreak5,ATLossStreak3,ATLossStreak5,HTGD,ATGD,DiffPts,DiffFormPts,DiffLP
0,H,0,0,0,0,0,0,M,M,M,...,0,0,0,0,0,0,0,0,0,-15.0
1,NH,0,0,0,0,0,0,M,M,M,...,0,0,0,0,0,0,0,0,0,10.0
2,NH,0,0,0,0,0,0,M,M,M,...,0,0,0,0,0,0,0,0,0,-16.0
3,NH,0,0,0,0,0,0,M,M,M,...,0,0,0,0,0,0,0,0,0,-1.0
4,NH,0,0,0,0,0,0,M,M,M,...,0,0,0,0,0,0,0,0,0,5.0

In [351]:
playing_stat.keys()

Index(['FTR', 'HTGS', 'ATGS', 'HTGC', 'ATGC', 'HTP', 'ATP', 'HM1', 'HM2',
       'HM3', 'HM4', 'HM5', 'AM1', 'AM2', 'AM3', 'AM4', 'AM5', 'MW',
       'HTWinStreak3', 'HTWinStreak5', 'HTLossStreak3', 'HTLossStreak5',
       'ATWinStreak3', 'ATWinStreak5', 'ATLossStreak3', 'ATLossStreak5',
       'HTGD', 'ATGD', 'DiffPts', 'DiffFormPts', 'DiffLP'],
      dtype='object')

In [352]:
# Scale DiffPts , DiffFormPts, HTGD, ATGD by Matchweek.
cols = ['HTGD','ATGD','DiffPts','DiffFormPts','HTP','ATP']

In [353]:
playing_stat.MW = playing_stat.MW.astype(float)

for col in cols:
    playing_stat[col] = playing_stat[col] / playing_stat.MW

In [354]:
# playing_stat.HTGS=(playing_stat.HTGS)/
playing_stat.HTGS=playing_stat.HTGS/playing_stat.HTGS.max()

In [355]:
playing_stat.ATGS=playing_stat.ATGS/playing_stat.ATGS.max()
playing_stat.HTGC=playing_stat.HTGC/playing_stat.HTGC.max()
playing_stat.ATGC=playing_stat.ATGC/playing_stat.ATGC.max()
playing_stat

,FTR,HTGS,ATGS,HTGC,ATGC,HTP,ATP,HM1,HM2,HM3,...,HTLossStreak5,ATWinStreak3,ATWinStreak5,ATLossStreak3,ATLossStreak5,HTGD,ATGD,DiffPts,DiffFormPts,DiffLP
0,H,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,M,M,M,...,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,-15.0
1,NH,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,M,M,M,...,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,10.0
2,NH,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,M,M,M,...,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,-16.0
3,NH,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,M,M,M,...,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,-1.0
4,NH,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,M,M,M,...,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,5.0
5,NH,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,M,M,M,...,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,5.0
6,NH,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,M,M,M,...,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,13.0
7,H,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,M,M,M,...,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,-11.0
8,NH,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,M,M,M,...,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,13.0
9,NH,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,M,M,M,...,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,17.0
10,NH,0.012346,0.000000,0.000000,0.028986,1.500000,0.000000,W,M,M,...,0,0,0,0,0,0.500000,-1.000000,1.500000,1.500000,-12.0
11,H,0.037037,0.025316,0.013699,0.028986,1.500000,0.500000,W,M,M,...,0,0,0,0,0,1.000000,0.000000,1.000000,1.000000,-17.0
12,NH,0.012346,0.000000,0.027397,0.014493,0.000000,0.000000,L,M,M,...,0,0,0,0,0,-0.500000,-0.500000,0.000000,0.000000,1.0
13,NH,0.024691,0.025316,0.027397,0.014493,0.500000,1.500000,D,M,M,...,0,0,0,0,0,0.000000,0.500000,-1.000000,-1.000000,5.0
14,NH,0.012346,0.025316,0.027397,0.028986,0.000000,0.500000,L,M,M,...,0,0,0,0,0,-0.500000,0.000000,-0.500000,-0.500000,0.0
15,H,0.024691,0.012658,0.013699,0.043478,1.500000,0.000000,W,M,M,...,0,0,0,0,0,0.500000,-1.000000,1.500000,1.500000,0.0
16,NH,0.012346,0.000000,0.000000,0.014493,1.500000,0.000000,W,M,M,...,0,0,0,0,0,0.500000,-0.500000,1.500000,1.500000,8.0
17,NH,0.024691,0.012658,0.027397,0.028986,0.500000,0.000000,D,M,M,...,0,0,0,0,0,0.000000,-0.500000,0.500000,0.500000,11.0
18,H,0.012346,0.000000,0.000000,0.014493,1.500000,0.000000,W,M,M,...,0,0,0,0,0,0.500000,-0.500000,1.500000,1.500000,-14.0
19,H,0.024691,0.025316,0.000000,0.014493,1.500000,1.500000,W,M,M,...,0,0,0,0,0,1.000000,0.500000,0.000000,0.000000,-2.0
20,NH,0.012346,0.025316,0.054795,0.043478,0.000000,0.333333,L,L,M,...,0,0,0,0,0,-1.000000,-0.333333,-0.333333,-0.333333,16.0
21,NH,0.049383,0.063291,0.054795,0.014493,0.666667,2.000000,D,D,M,...,0,0,0,0,0,0.000000,1.333333,-1.333333,-1.333333,7.0
22,NH,0.061728,0.012658,0.013699,0.028986,2.000000,0.333333,W,W,M,...,0,0,0,0,0,1.333333,-0.333333,1.666667,1.666667,-6.0
23,NH,0.000000,0.025316,0.027397,0.072464,0.333333,0.000000,D,L,M,...,0,0,0,0,0,-0.666667,-1.000000,0.333333,0.333333,0.0
24,H,0.000000,0.037975,0.068493,0.043478,0.000000,0.666667,L,L,M,...,0,0,0,0,0,-1.666667,0.000000,-0.666667,-0.666667,5.0
25,H,0.037037,0.025316,0.013699,0.028986,2.000000,0.666667,W,W,M,...,0,0,0,0,0,0.666667,0.000000,1.333333,1.333333,0.0
26,NH,0.037037,0.012658,0.027397,0.028986,1.000000,0.333333,W,L,M,...,0,0,0,0,0,0.333333,-0.333333,0.666667,0.666667,-1.0
27,H,0.012346,0.025316,0.000000,0.014493,1.333333,1.333333,D,W,M,...,0,0,0,0,0,0.333333,0.333333,0.000000,0.000000,-13.0
28,NH,0.024691,0.050633,0.054795,0.043478,0.333333,1.333333,L,D,M,...,0,0,0,0,0,-0.666667,0.333333,-1.000000,-1.000000,15.0
29,NH,0.061728,0.037975,0.000000,0.057971,2.000000,1.000000,W,W,M,...,0,0,0,0,0,1.666667,-0.333333,1.000000,1.000000,-3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2630,H,0.493827,0.759494,0.945205,0.579710,0.027778,0.000000,D,W,L,...,0,0,0,0,0,-0.805556,0.555556,0.027778,-0.111111,1.0
2631,H,0.839506,0.645570,0.575342,0.391304,0.083333,0.000000,W,W,L,...,0,0,0,0,0,0.722222,0.666667,0.083333,0.111111,-3.0
2632,NH,0.876543,0.493671,0.575342,0.666667,0.083333,0.000000,W,L,W,...,0,0,0,0,0,0.805556,-0.194444,0.083333,0.222222,2.0
2633,H,0.925926,0.329114,0.397260,0.652174,0.083333,0.027778,W,W,W,...,0,0,0,0,0,1.277778,-0.527778,0.055556,0.194444,-8.0
2634,NH,0.481481,0.860759,0.630137,0.608696,0.000000,0.083333,L,D,D,...,0,0,0,0,0,-0.194444,0.722222,-0.083333,-0.277778,4.0
2635,H,0.740741,0.468354,0.547945,0.840580,0.000000,0.000000,L,D,W,...,0,0,0,0,0,0.555556,-0.583333,0.000000,0.138889,-2.0
2636,NH,0.506173,0.949367,0.616438,0.420290,0.027778,0.083333,D,L,L,...,0,0,0,0,0,-0.111111,1.277778,-0.055556,-0.305556,4.0
2637,H,0.617284,0.443038,0.863014,0.710145,0.083333,0.083333,W,W,L,...,0,0,0,0,0,-0.361111,-0.388889,0.000000,0.000000,-2.0
2638,H,0.864198,0.569620,0.506849,0.782609,0.083333,0.083333,W,D,D,...,0,0,0,0,0,0.916667,-0.250000,0.000000,0.111111,3.0
2639,NH,0.320988,0.493671,0.616438,0.666667,0.027778,0.000000,D,W,L,...,0,0,0,0,0,-0.527778,-0.194444,0.027778,0.083333,12.0
2640,NH,0.481481,0.911392,0.712329,0.623188,0.027027,0.081081,D,D,L,...,0,0,0,0,0,-0.351351,0.783784,-0.054054,-0.189189,7.0
2641,NH,0.345679,0.518987,0.849315,1.000000,0.000000,0.081081,L,W,L,...,0,0,0,0,0,-0.918919,-0.756757,-0.081081,-0.081081,5.0
2642,H,0.567901,0.455696,0.835616,1.000000,0.000000,0.000000,L,L,L,...,0,0,0,0,0,-0.405405,-0.891892,0.000000,0.000000,-3.0
2643,H,0.901235,0.658228,0.328767,0.420290,0.081081,0.000000,W,L,W,...,0,0,0,0,0,1.324324,0.621622,0.081081,0.189189,-2.0
2644,NH,0.555556,0.898734,0.808219,0.608696,0.081081,0.027027,W,D,D,...,0,0,0,0,0,-0.378378,0.783784,0.054054,-0.027027,-1.0
2645,H,0.938272,0.468354,0.397260,0.855072,0.081081,0.000000,W,W,W,...,0,0,0,0,0,1.270270,-0.594595,0.081081,0.243243,-3.0
2646,H,0.888889,0.354430,0.589041,0.898551,0.081081,0.000000,W,W,W,...,0,0,0,0,0,0.783784,-0.918919,0.081081,0.216216,-15.0
2647,H,0.888889,0.518987,0.520548,0.666667,0.081081,0.000000,W,W,D,...,0,0,0,1,0,0.918919,-0.135135,0.081081,0.270270,-10.0
2648,NH,0.506173,0.658228,0.643836,0.420290,0.081081,0.000000,W,L,D,...,0,0,0,0,0,-0.162162,0.621622,0.081081,0.000000,1.0
2649,NH,0.567901,0.924051,0.767123,0.347826,0.000000,0.081081,L,W,W,...,0,1,0,0,0,-0.270270,1.324324,-0.081081,-0.135135,-2.0
2650,H,0.913580,0.772152,0.589041,0.594203,0.078947,0.078947,W,W,W,...,0,0,0,0,0,0.815789,0.526316,0.000000,0.131579,-9.0
2651,NH,0.469136,0.569620,0.726027,0.913043,0.000000,0.000000,L,D,W,...,0,0,0,0,0,-0.394737,-0.473684,0.000000,-0.052632,11.0
2652,H,0.987654,0.354430,0.438356,0.927536,0.078947,0.000000,W,W,W,...,0,0,0,0,0,1.263158,-0.947368,0.078947,0.315789,-7.0
2653,NH,0.444444,1.000000,1.000000,0.362319,0.000000,0.078947,L,L,D,...,0,0,0,0,0,-0.973684,1.421053,-0.078947,-0.210526,15.0
2654,NH,0.580247,0.683544,0.849315,0.956522,0.000000,0.078947,L,L,W,...,0,0,0,0,0,-0.394737,-0.315789,-0.078947,-0.105263,-15.0
2655,H,0.925926,0.341772,0.575342,0.724638,0.078947,0.000000,W,D,W,...,0,0,0,0,0,0.868421,-0.605263,0.078947,0.157895,-10.0
2656,H,0.641975,0.632911,0.397260,0.884058,0.026316,0.078947,D,L,L,...,0,0,0,0,0,0.605263,-0.289474,-0.052632,-0.078947,-10.0
2657,NH,0.506173,0.506329,0.643836,0.811594,0.026316,0.000000,D,W,L,...,0,0,0,0,0,-0.157895,-0.421053,0.026316,0.026316,-3.0
2658,H,0.530864,0.531646,0.945205,0.710145,0.078947,0.000000,W,W,D,...,0,0,0,0,0,-0.684211,-0.184211,0.078947,0.236842,-2.0
2659,NH,0.493827,0.949367,0.863014,0.565217,0.000000,0.078947,L,L,L,...,1,0,0,0,0,-0.605263,0.947368,-0.078947,-0.289474,9.0

In [356]:
playing_stat=playing_stat.drop(["MW"],axis=1)

In [357]:
playing_stat.shape

(2660, 30)

In [358]:
# Testing set (2015-16 season)
playing_stat_test = playing_stat[1860:]

In [359]:
playing_stat_test

,FTR,HTGS,ATGS,HTGC,ATGC,HTP,ATP,HM1,HM2,HM3,...,HTLossStreak5,ATWinStreak3,ATWinStreak5,ATLossStreak3,ATLossStreak5,HTGD,ATGD,DiffPts,DiffFormPts,DiffLP
1860,H,0.444444,0.455696,0.739726,0.826087,0.000000,0.000000,L,W,W,...,0,0,0,1,1,-0.514286,-0.600000,0.000000,0.342857,0.0
1861,H,0.580247,0.481013,0.506849,0.855072,0.000000,0.028571,L,D,W,...,0,0,0,0,0,0.285714,-0.600000,-0.028571,-0.028571,-11.0
1862,NH,0.728395,0.405063,0.465753,0.666667,0.000000,0.028571,L,L,W,...,0,0,0,1,0,0.714286,-0.400000,-0.028571,0.142857,-16.0
1863,H,0.345679,0.594937,0.684932,0.376812,0.085714,0.028571,W,D,L,...,0,0,0,0,0,-0.628571,0.600000,0.057143,0.000000,-5.0
1864,H,0.506173,0.493671,0.602740,0.608696,0.085714,0.028571,W,L,D,...,0,0,0,0,0,-0.085714,-0.085714,0.057143,0.142857,7.0
1865,H,0.518519,0.329114,0.575342,0.753623,0.028571,0.000000,D,L,D,...,0,0,0,0,0,0.000000,-0.742857,0.028571,0.114286,-1.0
1866,H,0.839506,0.531646,0.369863,0.681159,0.085714,0.000000,W,D,W,...,0,1,0,0,0,1.171429,-0.142857,0.085714,0.114286,-17.0
1867,NH,0.679012,0.886076,0.671233,0.521739,0.028571,0.085714,D,W,L,...,0,0,0,0,0,0.171429,0.971429,-0.057143,-0.028571,-1.0
1868,NH,0.395062,0.835443,0.616438,0.478261,0.085714,0.085714,W,W,L,...,0,1,0,0,0,-0.371429,0.942857,0.000000,-0.200000,16.0
1869,H,0.320988,0.531646,0.657534,0.608696,0.000000,0.028571,L,W,D,...,0,0,0,0,0,-0.628571,0.000000,-0.028571,-0.028571,-11.0
1870,NH,0.518519,0.746835,0.657534,0.507246,0.000000,0.000000,L,L,L,...,0,0,0,0,0,-0.166667,0.666667,0.000000,0.000000,16.0
1871,NH,0.567901,0.379747,0.630137,0.724638,0.000000,0.083333,L,W,W,...,0,0,0,0,0,0.000000,-0.555556,-0.083333,0.000000,-5.0
1872,NH,0.407407,0.329114,0.657534,0.768116,0.000000,0.000000,L,W,W,...,0,0,0,0,0,-0.416667,-0.750000,0.000000,0.138889,1.0
1873,H,0.481481,0.607595,0.739726,0.405797,0.083333,0.000000,W,L,W,...,0,0,0,0,0,-0.416667,0.555556,0.083333,0.222222,0.0
1874,NH,0.444444,0.417722,0.821918,0.666667,0.000000,0.083333,L,L,L,...,1,0,0,0,0,-0.666667,-0.361111,-0.083333,-0.194444,0.0
1875,H,0.481481,0.696203,0.602740,0.724638,0.000000,0.000000,L,D,W,...,0,0,0,0,0,-0.138889,0.138889,0.000000,0.000000,7.0
1876,NH,0.851852,0.620253,0.369863,0.550725,0.083333,0.083333,W,W,D,...,0,0,0,0,0,1.166667,0.305556,0.000000,0.166667,-6.0
1877,H,0.876543,0.493671,0.493151,0.884058,0.083333,0.000000,W,W,W,...,0,0,0,0,0,0.972222,-0.611111,0.083333,0.111111,-13.0
1878,NH,0.814815,0.544304,0.465753,0.637681,0.000000,0.083333,L,W,D,...,0,0,0,0,0,0.888889,-0.027778,-0.083333,0.000000,-15.0
1879,NH,0.320988,0.493671,0.726027,0.637681,0.000000,0.000000,L,L,L,...,0,0,0,0,0,-0.750000,-0.138889,0.000000,-0.111111,7.0
1880,NH,0.617284,0.544304,0.534247,0.724638,0.027027,0.000000,D,W,L,...,0,0,0,0,0,0.297297,-0.189189,0.027027,0.135135,-11.0
1881,H,0.481481,0.468354,0.917808,0.884058,0.000000,0.027027,L,L,D,...,0,0,0,1,0,-0.756757,-0.648649,-0.027027,0.027027,0.0
1882,H,0.592593,0.379747,0.410959,0.724638,0.000000,0.081081,L,L,D,...,0,0,0,0,0,0.486486,-0.540541,-0.081081,-0.162162,12.0
1883,NH,0.370370,0.518987,0.684932,0.782609,0.027027,0.081081,D,W,W,...,0,0,0,0,0,-0.540541,-0.351351,-0.054054,-0.108108,-5.0
1884,H,0.679012,0.417722,0.726027,0.710145,0.000000,0.000000,L,L,D,...,0,0,0,0,0,0.054054,-0.432432,0.000000,-0.054054,-15.0
1885,NH,0.530864,0.582278,0.589041,0.695652,0.000000,0.000000,L,W,D,...,0,0,0,0,0,0.000000,-0.054054,0.000000,-0.054054,9.0
1886,NH,0.753086,0.848101,0.493151,0.507246,0.081081,0.027027,W,L,L,...,0,0,0,0,0,0.675676,0.864865,0.054054,-0.054054,-1.0
1887,NH,0.543210,0.974684,0.602740,0.521739,0.081081,0.081081,W,W,W,...,0,0,0,0,0,0.000000,1.108108,0.000000,-0.054054,13.0
1888,H,0.419753,0.886076,0.643836,0.405797,0.027027,0.027027,D,W,D,...,0,0,0,0,0,-0.351351,1.135135,0.000000,-0.081081,17.0
1889,NH,0.827160,0.379747,0.479452,0.724638,0.027027,0.027027,D,L,W,...,0,0,0,0,0,0.864865,-0.540541,0.000000,0.000000,-10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2630,H,0.493827,0.759494,0.945205,0.579710,0.027778,0.000000,D,W,L,...,0,0,0,0,0,-0.805556,0.555556,0.027778,-0.111111,1.0
2631,H,0.839506,0.645570,0.575342,0.391304,0.083333,0.000000,W,W,L,...,0,0,0,0,0,0.722222,0.666667,0.083333,0.111111,-3.0
2632,NH,0.876543,0.493671,0.575342,0.666667,0.083333,0.000000,W,L,W,...,0,0,0,0,0,0.805556,-0.194444,0.083333,0.222222,2.0
2633,H,0.925926,0.329114,0.397260,0.652174,0.083333,0.027778,W,W,W,...,0,0,0,0,0,1.277778,-0.527778,0.055556,0.194444,-8.0
2634,NH,0.481481,0.860759,0.630137,0.608696,0.000000,0.083333,L,D,D,...,0,0,0,0,0,-0.194444,0.722222,-0.083333,-0.277778,4.0
2635,H,0.740741,0.468354,0.547945,0.840580,0.000000,0.000000,L,D,W,...,0,0,0,0,0,0.555556,-0.583333,0.000000,0.138889,-2.0
2636,NH,0.506173,0.949367,0.616438,0.420290,0.027778,0.083333,D,L,L,...,0,0,0,0,0,-0.111111,1.277778,-0.055556,-0.305556,4.0
2637,H,0.617284,0.443038,0.863014,0.710145,0.083333,0.083333,W,W,L,...,0,0,0,0,0,-0.361111,-0.388889,0.000000,0.000000,-2.0
2638,H,0.864198,0.569620,0.506849,0.782609,0.083333,0.083333,W,D,D,...,0,0,0,0,0,0.916667,-0.250000,0.000000,0.111111,3.0
2639,NH,0.320988,0.493671,0.616438,0.666667,0.027778,0.000000,D,W,L,...,0,0,0,0,0,-0.527778,-0.194444,0.027778,0.083333,12.0
2640,NH,0.481481,0.911392,0.712329,0.623188,0.027027,0.081081,D,D,L,...,0,0,0,0,0,-0.351351,0.783784,-0.054054,-0.189189,7.0
2641,NH,0.345679,0.518987,0.849315,1.000000,0.000000,0.081081,L,W,L,...,0,0,0,0,0,-0.918919,-0.756757,-0.081081,-0.081081,5.0
2642,H,0.567901,0.455696,0.835616,1.000000,0.000000,0.000000,L,L,L,...,0,0,0,0,0,-0.405405,-0.891892,0.000000,0.000000,-3.0
2643,H,0.901235,0.658228,0.328767,0.420290,0.081081,0.000000,W,L,W,...,0,0,0,0,0,1.324324,0.621622,0.081081,0.189189,-2.0
2644,NH,0.555556,0.898734,0.808219,0.608696,0.081081,0.027027,W,D,D,...,0,0,0,0,0,-0.378378,0.783784,0.054054,-0.027027,-1.0
2645,H,0.938272,0.468354,0.397260,0.855072,0.081081,0.000000,W,W,W,...,0,0,0,0,0,1.270270,-0.594595,0.081081,0.243243,-3.0
2646,H,0.888889,0.354430,0.589041,0.898551,0.081081,0.000000,W,W,W,...,0,0,0,0,0,0.783784,-0.918919,0.081081,0.216216,-15.0
2647,H,0.888889,0.518987,0.520548,0.666667,0.081081,0.000000,W,W,D,...,0,0,0,1,0,0.918919,-0.135135,0.081081,0.270270,-10.0
2648,NH,0.506173,0.658228,0.643836,0.420290,0.081081,0.000000,W,L,D,...,0,0,0,0,0,-0.162162,0.621622,0.081081,0.000000,1.0
2649,NH,0.567901,0.924051,0.767123,0.347826,0.000000,0.081081,L,W,W,...,0,1,0,0,0,-0.270270,1.324324,-0.081081,-0.135135,-2.0
2650,H,0.913580,0.772152,0.589041,0.594203,0.078947,0.078947,W,W,W,...,0,0,0,0,0,0.815789,0.526316,0.000000,0.131579,-9.0
2651,NH,0.469136,0.569620,0.726027,0.913043,0.000000,0.000000,L,D,W,...,0,0,0,0,0,-0.394737,-0.473684,0.000000,-0.052632,11.0
2652,H,0.987654,0.354430,0.438356,0.927536,0.078947,0.000000,W,W,W,...,0,0,0,0,0,1.263158,-0.947368,0.078947,0.315789,-7.0
2653,NH,0.444444,1.000000,1.000000,0.362319,0.000000,0.078947,L,L,D,...,0,0,0,0,0,-0.973684,1.421053,-0.078947,-0.210526,15.0
2654,NH,0.580247,0.683544,0.849315,0.956522,0.000000,0.078947,L,L,W,...,0,0,0,0,0,-0.394737,-0.315789,-0.078947,-0.105263,-15.0
2655,H,0.925926,0.341772,0.575342,0.724638,0.078947,0.000000,W,D,W,...,0,0,0,0,0,0.868421,-0.605263,0.078947,0.157895,-10.0
2656,H,0.641975,0.632911,0.397260,0.884058,0.026316,0.078947,D,L,L,...,0,0,0,0,0,0.605263,-0.289474,-0.052632,-0.078947,-10.0
2657,NH,0.506173,0.506329,0.643836,0.811594,0.026316,0.000000,D,W,L,...,0,0,0,0,0,-0.157895,-0.421053,0.026316,0.026316,-3.0
2658,H,0.530864,0.531646,0.945205,0.710145,0.078947,0.000000,W,W,D,...,0,0,0,0,0,-0.684211,-0.184211,0.078947,0.236842,-2.0
2659,NH,0.493827,0.949367,0.863014,0.565217,0.000000,0.078947,L,L,L,...,1,0,0,0,0,-0.605263,0.947368,-0.078947,-0.289474,9.0

In [360]:
playing_stat=playing_stat[:1860]

In [361]:
playing_stat.shape

(1860, 30)

In [362]:
playing_stat.to_csv(loc + "final_dataset.csv",index=None)
playing_stat_test.to_csv(loc+"test.csv",index=None)

req_cols=["FTR","HTP","ATP","HM1","HM2","HM3","AM1","AM2","AM3","HTGD","ATGD","DiffFormPts","DiffLP"]
playing_stat=playing_stat[req_cols]
playing_stat_test=playing_stat_test[req_cols]